# Generated by Django 5.2.4 on 2025-08-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_feedback_image_alter_items_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='Booking_date',
            field=models.DateField(null=True),
        ),
    ]
